services:
  api:
    # Build from current directory
    build: .
    container_name: crux-api
    # Run the server on port 8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # Sync local files to container for hot-reloading
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Load environment variables from the .env file
    env_file:
      - .env
    # Ensure API starts after Database
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: crux-db
    # restart: always
    # Map .env variables to the Postgres container environment
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# for persisting Postgres data
# clear using `docker-compose down -v`
volumes:
  postgres_data:
