services:
  api:
    # Build from current directory
    build: .
    container_name: crux-api
    # Run the server on port 8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # Sync local files to container for hot-reloading
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Load environment variables from the .env file
    env_file:
      - .env
    # Ensure API starts after Database
    depends_on:
      - db
      - minio

  db:
    image: postgres:15-alpine
    container_name: crux-db
    # restart: always
    # Map .env variables to the Postgres container environment
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: crux-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  # One-off job to create the bucket automatically
  createbuckets:
    image: minio/mc
    container_name: crux-createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " 
        /usr/bin/mc alias set crux http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; 
        if ! /usr/bin/mc ls crux/${S3_BUCKET_NAME}; 
        then
          /usr/bin/mc mb crux/${S3_BUCKET_NAME};
          /usr/bin/mc anonymous set public crux/${S3_BUCKET_NAME};
        else
          echo 'Bucket already exists';
        fi 
      exit 0; "

# for persisting Postgres data
# clear using `docker-compose down -v`
volumes:
  postgres_data:
  minio_data:
